
 

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: General point run Scrapers

on:
  #  push:
  #    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 7:00 AM CET / 8:00 AM CEST
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        
        pip3 install -r requirements.txt

    - name: All scrapers runs
    #TODO to remove line 36 and 37
      env:
        IURIE: ${{ secrets.IURIE }}
      run: |
        python3 sites/__main_RunnerFile.py